/**
 * @module vortez-io
 * @author NetFeez <netfeez.dev@gmail.com>
 * @license Apache-2.0
 * @description Isomorphic UUID v4 generator.
 *
 *              ⚠️ IMPORTANT: READ THIS BEFORE USING.
 *              
 *              IS NO LONGER CRYPTOGRAPHICALLY SECURE.
 *              This module provides a fallback implementation of UUID v4 generation using a Linear Congruential Generator (LCG) algorithm
 *              The generated UUIDs are suitable for non-cryptographic use cases, such as generating unique identifiers for events or requests within the Vortez IO protocol, but should not be used in security-sensitive contexts.
 */
export class UUID {
    private static seed = UUID.initSeed();

    private static readonly HEX_TABLE = Array.from(
        { length: 256 },
        (_, i) => i.toString(16).padStart(2, '0')
    );

    /**
     * Initialize the seed for the LCG fallback using a combination of current time and random value.
     * This ensures that the generated UUIDs are not the same across different runs of the application, even in fallback mode.
     * @returns A 32-bit unsigned integer to be used as the initial seed for the LCG.
     */
    private static initSeed(): number {
        return (Date.now() ^ Math.floor(Math.random() * 0xffffffff) ) >>> 0;
    }

    /**
     * Generate the next 32-bit unsigned integer using a Linear Congruential Generator (LCG) algorithm.
     * This method is used as a fallback for generating random values when crypto APIs are not available.
     * The LCG parameters are chosen to provide a reasonable period and distribution for non-cryptographic use cases.
     * @returns A 32-bit unsigned integer generated by the LCG algorithm.
     */
    private static next32(): number {
        UUID.seed = (1664525 * UUID.seed + 1013904223) >>> 0;
        return UUID.seed;
    }

    /**
     * Generate a UUID v4 string in the format xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.
     * This method uses the createRaw() method to generate a 16-byte Uint8Array and then converts it to the standard UUID string format.
     * @returns A string representation of the generated UUID.
     */
    public static create(): string {
        return this.binToUuid(this.createRaw());
    }

    /**
     * Generate a 16-byte Uint8Array containing a UUID v4.
     * This method uses the LCG fallback to generate random values when crypto APIs are not available.
     * @returns A Uint8Array containing the 16 bytes of the UUID.
     */
    public static createRaw(): Uint8Array {
        const bytes = new Uint8Array(16);

        for (let i = 0; i < 16; i += 4) {
            const n = UUID.next32();

            bytes[i]     = (n >>> 24) & 0xff;
            bytes[i + 1] = (n >>> 16) & 0xff;
            bytes[i + 2] = (n >>> 8) & 0xff;
            bytes[i + 3] = n & 0xff;
        }
        bytes[6] = (bytes[6] & 0x0f) | 0x40;
        bytes[8] = (bytes[8] & 0x3f) | 0x80;

        return bytes;
    }

    /**
     * Convert a 16-byte Uint8Array to a UUID string in the format xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.
     * @param bin A Uint8Array containing the 16 bytes of the UUID.
     * @returns A string representation of the UUID.
     */
    public static binToUuid(bin: Uint8Array): string {
        const hex = UUID.HEX_TABLE;

        return (
            hex[bin[0]] + hex[bin[1]] + hex[bin[2]] + hex[bin[3]] + "-" +
            hex[bin[4]] + hex[bin[5]] + "-" +
            hex[bin[6]] + hex[bin[7]] + "-" +
            hex[bin[8]] + hex[bin[9]] + "-" +
            hex[bin[10]] + hex[bin[11]] + hex[bin[12]] +
            hex[bin[13]] + hex[bin[14]] + hex[bin[15]]
        );
    }
    /**
     * Convert a UUID string in the format xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx to a 16-byte Uint8Array.
     * @param uuid A string representation of the UUID.
     * @returns A Uint8Array containing the 16 bytes of the UUID.
     */
    public static uuidToBin(uuid: string): Uint8Array {
        const hex = UUID.HEX_TABLE;
        const bin = new Uint8Array(16);

        const parts = uuid.split('-');
        if (parts.length !== 5) throw new Error(`Invalid UUID format: ${uuid}`);

        const hexStr = parts.join('');
        if (hexStr.length !== 32) throw new Error(`Invalid UUID format: ${uuid}`);

        for (let i = 0; i < 16; i++) {
            const byteHex = hexStr.substr(i * 2, 2);
            const byteValue = parseInt(byteHex, 16);
            if (isNaN(byteValue)) throw new Error(`Invalid UUID format: ${uuid}`);
            bin[i] = byteValue;
        }
        return bin;
    }
    /**
     * Validate whether a given string is a valid UUID v4 according to the standard format and version/type bits.
     * This method checks that the string matches the expected pattern for UUID v4, including the correct placement of hyphens and the specific bits that indicate version 4 and the variant.
     * @param uuid The string to validate as a UUID v4.
     * @returns True if the input string is a valid UUID v4, false otherwise.
     */
    public static isValid(uuid: string): boolean {
        const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
        return uuidRegex.test(uuid);
    }
}

export namespace UUID {}
export default UUID;